// Locale translation engine for *.objects.generated.ts files.
// Reads the EN structure, replaces ONLY right-hand-side string values via
// per-locale dictionaries, and writes byte-identical structure (keys,
// whitespace, comments, escapes) to the target locale file.

import { readFileSync, writeFileSync } from 'node:fs';

// Pattern: leading whitespace, key (ident or "quoted"), colon, "value", optional trailing comma.
// value capture group preserves backslash escapes (e.g., \" inside string).
const LINE_RE = /^(\s*(?:[A-Za-z_][\w]*|"[^"]+")\s*:\s*)"((?:[^"\\]|\\.)*)"(,?\s*)$/;

const HEADER_RE = /Auto-generated by 'os i18n extract' for locale '[^']+'\./;

function translateFile(srcPath, dstPath, dict, headerLocale, exportName) {
  const src = readFileSync(srcPath, 'utf8');
  const out = [];
  const missing = new Set();
  let translated = 0;
  let total = 0;
  for (const line of src.split('\n')) {
    const m = line.match(LINE_RE);
    if (!m) {
      out.push(line);
      continue;
    }
    total++;
    const [, prefix, value, suffix] = m;
    const t = dict[value];
    if (t == null) {
      missing.add(value);
      out.push(line); // leave English as fallback
    } else {
      translated++;
      out.push(`${prefix}"${t}"${suffix}`);
    }
  }
  let result = out.join('\n');
  // Rewrite header line + export identifier.
  result = result.replace(
    HEADER_RE,
    `Auto-generated by 'os i18n extract' for locale '${headerLocale}'.`,
  );
  result = result.replace(
    /export const \w+Objects: NonNullable<TranslationData\['objects'\]> = \{/,
    `export const ${exportName}: NonNullable<TranslationData['objects']> = {`,
  );
  writeFileSync(dstPath, result);
  return { translated, total, missing: [...missing] };
}

import { zhCN } from './dict-zh-CN.mjs';
import { jaJP } from './dict-ja-JP.mjs';
import { esES } from './dict-es-ES.mjs';

const base = 'packages/platform-objects/src/apps/translations';
const enPath = `${base}/en.objects.generated.ts`;

for (const [loc, dict, headerLocale, exportName, outName] of [
  ['zh-CN', zhCN, 'zh-CN', 'zhCNObjects', 'zh-CN.objects.generated.ts'],
  ['ja-JP', jaJP, 'ja-JP', 'jaJPObjects', 'ja-JP.objects.generated.ts'],
  ['es-ES', esES, 'es-ES', 'esESObjects', 'es-ES.objects.generated.ts'],
]) {
  const r = translateFile(enPath, `${base}/${outName}`, dict, headerLocale, exportName);
  console.log(
    `${loc}: translated ${r.translated}/${r.total} lines, missing ${r.missing.length} unique strings`,
  );
  if (r.missing.length) {
    console.log('  Missing samples:');
    for (const m of r.missing.slice(0, 20)) console.log(`    ${JSON.stringify(m)}`);
  }
}
