/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PackageRouteImport } from './routes/$package'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PackageIndexRouteImport } from './routes/$package.index'
import { Route as PackagePublicFormsRouteImport } from './routes/$package.public-forms'
import { Route as PackageObjectsNameRouteImport } from './routes/$package.objects.$name'
import { Route as PackageMetadataTypeNameRouteImport } from './routes/$package.metadata.$type.$name'

const PackageRoute = PackageRouteImport.update({
  id: '/$package',
  path: '/$package',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PackageIndexRoute = PackageIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PackageRoute,
} as any)
const PackagePublicFormsRoute = PackagePublicFormsRouteImport.update({
  id: '/public-forms',
  path: '/public-forms',
  getParentRoute: () => PackageRoute,
} as any)
const PackageObjectsNameRoute = PackageObjectsNameRouteImport.update({
  id: '/objects/$name',
  path: '/objects/$name',
  getParentRoute: () => PackageRoute,
} as any)
const PackageMetadataTypeNameRoute = PackageMetadataTypeNameRouteImport.update({
  id: '/metadata/$type/$name',
  path: '/metadata/$type/$name',
  getParentRoute: () => PackageRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$package': typeof PackageRouteWithChildren
  '/$package/public-forms': typeof PackagePublicFormsRoute
  '/$package/': typeof PackageIndexRoute
  '/$package/objects/$name': typeof PackageObjectsNameRoute
  '/$package/metadata/$type/$name': typeof PackageMetadataTypeNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$package/public-forms': typeof PackagePublicFormsRoute
  '/$package': typeof PackageIndexRoute
  '/$package/objects/$name': typeof PackageObjectsNameRoute
  '/$package/metadata/$type/$name': typeof PackageMetadataTypeNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$package': typeof PackageRouteWithChildren
  '/$package/public-forms': typeof PackagePublicFormsRoute
  '/$package/': typeof PackageIndexRoute
  '/$package/objects/$name': typeof PackageObjectsNameRoute
  '/$package/metadata/$type/$name': typeof PackageMetadataTypeNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$package'
    | '/$package/public-forms'
    | '/$package/'
    | '/$package/objects/$name'
    | '/$package/metadata/$type/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$package/public-forms'
    | '/$package'
    | '/$package/objects/$name'
    | '/$package/metadata/$type/$name'
  id:
    | '__root__'
    | '/'
    | '/$package'
    | '/$package/public-forms'
    | '/$package/'
    | '/$package/objects/$name'
    | '/$package/metadata/$type/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PackageRoute: typeof PackageRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$package': {
      id: '/$package'
      path: '/$package'
      fullPath: '/$package'
      preLoaderRoute: typeof PackageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$package/': {
      id: '/$package/'
      path: '/'
      fullPath: '/$package/'
      preLoaderRoute: typeof PackageIndexRouteImport
      parentRoute: typeof PackageRoute
    }
    '/$package/public-forms': {
      id: '/$package/public-forms'
      path: '/public-forms'
      fullPath: '/$package/public-forms'
      preLoaderRoute: typeof PackagePublicFormsRouteImport
      parentRoute: typeof PackageRoute
    }
    '/$package/objects/$name': {
      id: '/$package/objects/$name'
      path: '/objects/$name'
      fullPath: '/$package/objects/$name'
      preLoaderRoute: typeof PackageObjectsNameRouteImport
      parentRoute: typeof PackageRoute
    }
    '/$package/metadata/$type/$name': {
      id: '/$package/metadata/$type/$name'
      path: '/metadata/$type/$name'
      fullPath: '/$package/metadata/$type/$name'
      preLoaderRoute: typeof PackageMetadataTypeNameRouteImport
      parentRoute: typeof PackageRoute
    }
  }
}

interface PackageRouteChildren {
  PackagePublicFormsRoute: typeof PackagePublicFormsRoute
  PackageIndexRoute: typeof PackageIndexRoute
  PackageObjectsNameRoute: typeof PackageObjectsNameRoute
  PackageMetadataTypeNameRoute: typeof PackageMetadataTypeNameRoute
}

const PackageRouteChildren: PackageRouteChildren = {
  PackagePublicFormsRoute: PackagePublicFormsRoute,
  PackageIndexRoute: PackageIndexRoute,
  PackageObjectsNameRoute: PackageObjectsNameRoute,
  PackageMetadataTypeNameRoute: PackageMetadataTypeNameRoute,
}

const PackageRouteWithChildren =
  PackageRoute._addFileChildren(PackageRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PackageRoute: PackageRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
